repos:
    - repo: https://github.com/cybozu/pre-commit-jsonnet
      rev: HEAD
      hooks:
          - id: jsonnet-fmt
            args: ["--test"]
          - id: jsonnet-lint
            args: ["--jpath", "lib/"]
