name: Run lint and tests

on:
  pull_request:
  push:

env:
  go-version: 1.24

jobs:
  unit-test:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go-version }}

      - name: Setup
        run: make setup

      - name: Run lint
        run: make lint

      - name: Run tests
        run: make test
